# Generated by Django 2.2.2 on 2020-05-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20200518_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinguser',
            name='game_session_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
