# Generated by Django 2.2.2 on 2020-05-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_waitinguser_game_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player_1_connected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_2_connected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
